title: ASM - the Android Studio Mobile.

author: ASM Team
#email: your-email@domain.com
description: Code, Build, and Run on your mobile device.

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
